update dotfiles
git: reset to branch and cherry pick last commits in bash, fish powershell
* this would not be necessary and less broken, if I use jujutsu

powershell: document error behavior checks

llm: tensorzero question on knowledge distribution based on leap71 interview

formal modeling: books of promising

docker compose pieces

more keycloak pieces

linker stubs for .so as .ifi:
* Soonish Zig will make a linker api and object format extension, which
  hopefully will become a simplified standard without linker scripts.
* Hopefully this fixes lib packaging and development for native platform
  code and zig and offers saner linker errors including for static libs.

diff --git a/.config/shells/bash_aliases b/.config/shells/bash_aliases
--- a/.config/shells/bash_aliases
+++ b/.config/shells/bash_aliases
@@ -31,3 +31,23 @@ makeWorkTree() {
   echo "gitdir: ./.bare" > .git
   git worktree add master
 }
+
+# reset to branch $1 and apply last $2 commits
+# success: exist code 0
+# failure: revert, exit code 1
+resetToBranchAndCherryPickLastCommits() {
+  #current_branch=$(git symbolic-ref --short HEAD)
+  git show-ref --quiet --branches "$1" || (echo "no branch $1"; return)
+  [ "$2" -gt 0 ] 2>/dev/null || (echo "$2 <= 0 or no number"; return)
+  commits=$(git log HEAD~"$2"..HEAD --reverse --format="%H")
+  test -z "$commits" && (echo "empty commits"; return)
+  original_head=$(git rev-parse HEAD)
+  prev_head=$(git rev-parse HEAD~"$2")
+  git reset --hard "$1" || return
+  # must now revert on failure
+  if ! git cherry-pick "$prev_head".."$original_head"; then
+    echo "cherry-pick failed, reverting.."
+    git cherry-pick --abort 2>/dev/null || true
+    git reset --hard "$original_head"
+  fi
+}
